apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task2
  name: task2
spec:
  selector:
    matchLabels:
      app: task2
  replicas: 1
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nfsvol
          mountPath: /share
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: my-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
